import React from 'react';
import { Modal, Input, Button, Combobox, Field } from '@grafana/ui';
import { formatEdgeId, toOptional } from '../../core/builderMode';
import { useModalForm } from '../../hooks/useModalForm';

export interface EdgeFormModalProps {
  isOpen: boolean;
  sourceNodeId: string | null;
  targetNodeId?: string | null;
  existingNodeIds: string[];
  existingEdgeIds: string[];
  onSubmit: (
    sourceNodeId: string,
    targetNodeId: string,
    edgeId?: string,
    edgeLabel?: string,
    sourcePort?: string,
    targetPort?: string
  ) => void;
  onDismiss: () => void;
}

export const EdgeFormModal: React.FC<EdgeFormModalProps> = ({
  isOpen,
  sourceNodeId,
  targetNodeId,
  existingNodeIds,
  existingEdgeIds,
  onSubmit,
  onDismiss,
}) => {
  const { values, error, setError, handleChange, resetForm } = useModalForm({
    selectedSourceNodeId: sourceNodeId || ('' as string | undefined),
    sourcePort: '',
    targetNodeId: targetNodeId || (undefined as string | undefined),
    targetPort: '',
    edgeId: '',
    edgeLabel: '',
  });

  const handleSubmit = () => {
    if (!values.selectedSourceNodeId) {
      setError('Source node is required');
      return;
    }

    if (!values.targetNodeId) {
      setError('Target node is required');
      return;
    }

    const autoGeneratedEdgeId = formatEdgeId(
      values.selectedSourceNodeId,
      values.targetNodeId,
      toOptional(values.sourcePort),
      toOptional(values.targetPort)
    );
    if (existingEdgeIds.includes(autoGeneratedEdgeId)) {
      setError('Edge already exists between these nodes');
      return;
    }

    onSubmit(
      values.selectedSourceNodeId,
      values.targetNodeId,
      toOptional(values.edgeId),
      toOptional(values.edgeLabel),
      toOptional(values.sourcePort),
      toOptional(values.targetPort)
    );

    resetForm();
  };

  const handleDismiss = () => {
    resetForm();
    onDismiss();
  };

  const effectiveSourceId = values.selectedSourceNodeId || sourceNodeId;
  const hasTargetError = error.includes('Target') || error.includes('Edge already exists');
  const isTargetFieldInvalid = !!error && hasTargetError;

  return (
    <Modal
      isOpen={isOpen}
      title={sourceNodeId ? `Add Edge from ${sourceNodeId}` : 'Add Edge'}
      onDismiss={handleDismiss}
    >
      {!sourceNodeId && (
        <Field
          label="Source Node"
          required
          invalid={!!error && !values.selectedSourceNodeId}
          error={!values.selectedSourceNodeId ? error : undefined}
        >
          <Combobox
            data-testid="edge-form-source-select"
            options={existingNodeIds.map((id) => ({ label: id, value: id }))}
            placeholder="Select source node"
            value={values.selectedSourceNodeId}
            onChange={(val) => handleChange('selectedSourceNodeId')(val?.value)}
          />
        </Field>
      )}

      <Field label="Source Port (optional)" description="Port name on source node (for record shapes or HTML tables).">
        <Input
          data-testid="edge-form-source-port-input"
          placeholder="E.g. 'port1', 'f0', 'http'"
          value={values.sourcePort}
          onChange={(e) => handleChange('sourcePort')(e.currentTarget.value)}
        />
      </Field>

      <Field label="Target Node" required invalid={isTargetFieldInvalid} error={hasTargetError ? error : undefined}>
        <Combobox
          data-testid="edge-form-target-select"
          options={existingNodeIds.filter((id) => id !== effectiveSourceId).map((id) => ({ label: id, value: id }))}
          placeholder="Select target node"
          value={values.targetNodeId}
          onChange={(val) => handleChange('targetNodeId')(val?.value)}
          disabled={!!targetNodeId}
        />
      </Field>

      <Field label="Target Port (optional)" description="Port name on target node (for record shapes or HTML tables).">
        <Input
          data-testid="edge-form-target-port-input"
          placeholder="E.g. 'port2', 'f1', 'https'"
          value={values.targetPort}
          onChange={(e) => handleChange('targetPort')(e.currentTarget.value)}
        />
      </Field>

      <Field
        label="Edge ID"
        description="Leave empty to auto-generate. Used to identify the edge when defining overrides E.g. 'server1_to_server2'."
      >
        <Input
          data-testid="edge-form-id-input"
          autoFocus
          placeholder={
            values.targetNodeId && effectiveSourceId
              ? formatEdgeId(
                  effectiveSourceId,
                  values.targetNodeId,
                  toOptional(values.sourcePort),
                  toOptional(values.targetPort)
                )
              : 'Auto'
          }
          value={values.edgeId}
          onChange={(e) => handleChange('edgeId')(e.currentTarget.value)}
        />
      </Field>
      <Field label="Edge Label (optional)" description="Text to display on the edge.">
        <Input
          data-testid="edge-form-label-input"
          placeholder="E.g. 'Server 1 to Server 2'"
          value={values.edgeLabel}
          onChange={(e) => handleChange('edgeLabel')(e.currentTarget.value)}
        />
      </Field>

      <Modal.ButtonRow>
        <Button variant="secondary" onClick={handleDismiss}>
          Cancel
        </Button>
        <Button variant="primary" onClick={handleSubmit}>
          Add Edge
        </Button>
      </Modal.ButtonRow>
    </Modal>
  );
};
