FROM mcr.microsoft.com/playwright:v1.58.2-noble@sha256:6446946a1d9fd62d9ae501312a2d76a43ee688542b21622056a372959b65d63d

WORKDIR /app

RUN npm install "@playwright/test@1.58.2" "dotenv@^16.3.1" "@grafana/plugin-e2e" "monocart-reporter"

CMD ["npx", "playwright", "test", "-c", "playwright.config.ts"]
