import React from 'react';
import { Modal, Input, Button, Combobox, Field } from '@grafana/ui';
import { formatEdgeId, toOptional } from '../builderMode';
import { useModalForm } from '../hooks/useModalForm';

export interface EdgeFormModalProps {
  isOpen: boolean;
  sourceNodeId: string | null;
  targetNodeId?: string | null;
  existingNodeIds: string[];
  existingEdgeIds: string[];
  onSubmit: (sourceNodeId: string, targetNodeId: string, edgeId?: string, edgeLabel?: string) => void;
  onDismiss: () => void;
}

export const EdgeFormModal: React.FC<EdgeFormModalProps> = ({
  isOpen,
  sourceNodeId,
  targetNodeId,
  existingNodeIds,
  existingEdgeIds,
  onSubmit,
  onDismiss,
}) => {
  const { values, error, setError, handleChange, resetForm } = useModalForm({
    selectedSourceNodeId: sourceNodeId || ('' as string | undefined),
    targetNodeId: targetNodeId || (undefined as string | undefined),
    edgeId: '',
    edgeLabel: '',
  });

  const handleSubmit = () => {
    if (!values.selectedSourceNodeId) {
      setError('Source node is required');
      return;
    }

    if (!values.targetNodeId) {
      setError('Target node is required');
      return;
    }

    const autoGeneratedEdgeId = formatEdgeId(values.selectedSourceNodeId, values.targetNodeId);
    if (existingEdgeIds.includes(autoGeneratedEdgeId)) {
      setError('Edge already exists between these nodes');
      return;
    }

    onSubmit(values.selectedSourceNodeId, values.targetNodeId, toOptional(values.edgeId), toOptional(values.edgeLabel));

    resetForm();
  };

  const handleDismiss = () => {
    resetForm();
    onDismiss();
  };

  const effectiveSourceId = values.selectedSourceNodeId || sourceNodeId;

  return (
    <Modal
      isOpen={isOpen}
      title={sourceNodeId ? `Add Edge from ${sourceNodeId}` : 'Add Edge'}
      onDismiss={handleDismiss}
    >
      {!sourceNodeId && (
        <Field
          label="Source Node"
          required
          invalid={!!error && !values.selectedSourceNodeId}
          error={!values.selectedSourceNodeId ? error : undefined}
        >
          <Combobox
            options={existingNodeIds.map((id) => ({ label: id, value: id }))}
            placeholder="Select source node"
            value={values.selectedSourceNodeId}
            onChange={(val) => handleChange('selectedSourceNodeId')(val?.value)}
          />
        </Field>
      )}

      <Field
        label="Target Node"
        required
        invalid={!!error && error.includes('Target')}
        error={error.includes('Target') ? error : undefined}
      >
        <Combobox
          options={existingNodeIds.filter((id) => id !== effectiveSourceId).map((id) => ({ label: id, value: id }))}
          placeholder="Select target node"
          value={values.targetNodeId}
          onChange={(val) => handleChange('targetNodeId')(val?.value)}
          disabled={!!targetNodeId}
        />
      </Field>
      <Field label="Edge ID" description="Leave empty to auto-generate. Used to identify the edge when defining overrides E.g. 'server1_to_server2'.">
        <Input
          autoFocus
          placeholder={
            values.targetNodeId && effectiveSourceId
              ? formatEdgeId(effectiveSourceId, values.targetNodeId)
              : 'Auto'
          }
          value={values.edgeId}
          onChange={(e) => handleChange('edgeId')(e.currentTarget.value)}
        />
      </Field>
      <Field label="Edge Label (optional)" description="Text to display on the edge.">
        <Input
          placeholder="E.g. 'Server 1 to Server 2'"
          value={values.edgeLabel}
          onChange={(e) => handleChange('edgeLabel')(e.currentTarget.value)}
        />
      </Field>

      <Modal.ButtonRow>
        <Button variant="secondary" onClick={handleDismiss}>
          Cancel
        </Button>
        <Button variant="primary" onClick={handleSubmit}>
          Add Edge
        </Button>
      </Modal.ButtonRow>
    </Modal>
  );
};
