services:
  grafana:
    user: root
    container_name: 'grafana-graphviz-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.4.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/grafana-graphviz-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/grafana-graphviz-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-graphviz-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-graphviz-panel

    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
